### PR TITLE
Fixes #74: Adds ability to set lookback days and a default of 100

### LINKED ISSUE #74: Lookback Days
## Description

Users are seeing a "Pending" status even after the first run and fetch for a monitor has been defined and run. There are no metrics showing.

This normally occurs if there is no data in the table OR when the data is older than 100 days. Unfortunately, there was a change which allowed for greater granularity to go from days to minutes, and in doing so we changed from 100 days to 10,000 minutes. 

Unfortunately, this means the lookback is only 6 days now accordingly.

## Expected behavior

Ideally the default lookback is 100 days, and the user can specify the number of lookback days in the case that it is greater or less than this number of days worth of data they would like to monitor.

## Steps to reproduce

1. Start Monosi
2. Get a dataset with data where all timestamp fields are greater than 6 days
3. Create a monitor on that dataset
4. No data / metrics will show

Originally discovered / brought to attention by @tawfiq9009 , many thanks - will be fixing shortly.

### PR DESCRIPTION
**Pull request by unkrich**
## Issue

Described in #74 

## Screenshots

image

### CODE REVIEW

File: src/ui/src/pages/app/bootstrap_monitors/Index/components/MonitorForm/index.tsx [hunk 1]
```diff
@@ -23,6 +23,7 @@ const MonitorForm: React.FC = () => {
   const [type, setType] = useState<any>('table_health');
   const [database, setDatabase] = useState<any>('');
   const [schema, setSchema] = useState<any>('');
+  const [daysAgo, setDaysAgo] = useState<any>(100);
```
Comment (iporollo) [inline src/ui/src/pages/app/bootstrap_monitors/Index/components/MonitorForm/index.tsx:26]: The type here should technically be number since the input is a number

File: src/ui/src/pages/app/bootstrap_monitors/Index/components/MonitorForm/index.tsx [hunk 2]
```diff
@@ -80,6 +82,11 @@ const MonitorForm: React.FC = () => {
           <Form.Control type="text" placeholder="TPCH_SF1000" disabled value={schema} />
         </Form.Group>
 
+        <Form.Group className="mb-3" controlId="formBasicSchema">
+          <Form.Label>Lookback Days (# Days Ago to Fetch)</Form.Label>
+          <Form.Control type="number" value={daysAgo} onChange={(e: any) => setDaysAgo(e.target.value)} />
```
Comment (iporollo) [inline src/ui/src/pages/app/bootstrap_monitors/Index/components/MonitorForm/index.tsx:87]: We should be able to type this as `HTMLInputElement` just so we avoid `any`

File: src/core/models/monitor.py [hunk 3]
```diff
@@ -20,6 +20,7 @@ class MsiMonitor(DataClassDictMixin):
     timestamp_field: str = field(default=None, metadata={"sa": Column(String(100))})
     workspace: str = field(default=None, metadata={"sa": Column(String(100))})
     source: str = field(default=None, metadata={"sa": Column(String(100))})
+    days_ago: int = field(default=100, metadata={"sa": Column(Integer)})
```
Comment (iporollo) [inline src/core/models/monitor.py:23]: does this automatically update the expectations of the API request body?

**Review by iporollo — APPROVED** [review]
LGTM, 1 question and the comments on types are non-blocking

File: src/ui/src/pages/app/bootstrap_monitors/Index/components/MonitorForm/index.tsx (hunk 1 above)
Comment (unkrich) [reply src/ui/src/pages/app/bootstrap_monitors/Index/components/MonitorForm/index.tsx:26]: The type for the others should technically be string since the input is a string. Filed under technical debt not related to this change, but a good callout, and no reason not to improve the code as we write it.

File: src/ui/src/pages/app/bootstrap_monitors/Index/components/MonitorForm/index.tsx (hunk 2 above)
Comment (unkrich) [reply src/ui/src/pages/app/bootstrap_monitors/Index/components/MonitorForm/index.tsx:87]: Same as above

File: src/core/models/monitor.py (hunk 3 above)
Comment (unkrich) [reply src/core/models/monitor.py:23]: Yes, thanks to the magic of DataClassDictMixin and SQLAlchemy
